{% set name = "c-progressbar" %}
{% set version = "0.1.9" %}
{% set sha256 = "201a574481ab1dff55cc6c7ca6e34f96b25b04c1390330ab00491f2ee45f8d80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/progressbar/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - python  # [win]
    - toolchain
    - cmake
    - ncurses 5.9  # [not win]
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]
  run:
    - ncurses 5.9  # [not win]
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -e $PREFIX/lib/libprogressbar.so  # [linux]
    - test -e $PREFIX/lib/libprogressbar_static.a  # [linux]
    - test -e $PREFIX/lib/libprogressbar.dylib  # [osx]
    - test -e $PREFIX/lib/libprogressbar_static.a  # [osx]
    - if NOT exist %PREFIX%/lib/progressbar.lib exit 1  # [win]
    - if NOT exist %PREFIX%/lib/progressbar.dll exit 1  # [win]
    - if NOT exist %PREFIX%/lib/progressbar_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/progressbar
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'C library for displaying text progress bars'
  dev_url: https://github.com/limix/progressbar

extra:
  recipe-maintainers:
    - Horta
