{% set name = "c-progressbar" %}
{% set version = "0.1.11" %}
{% set sha256 = "8e3b8cd0b3f9cfb3a1dd3e2f47bd78dd7e727b1a90f824e19e11c2438bb5afe4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/progressbar/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - ncurses      # [not win]
  run:
    - ncurses      # [not win]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -e $PREFIX/lib/libprogressbar.so  # [linux]
    - test -e $PREFIX/lib/libprogressbar_static.a  # [linux]
    - test -e $PREFIX/lib/libprogressbar.dylib  # [osx]
    - test -e $PREFIX/lib/libprogressbar_static.a  # [osx]
    - if NOT exist %PREFIX%/lib/progressbar.lib exit 1  # [win]
    - if NOT exist %PREFIX%/bin/progressbar.dll exit 1  # [win]
    - if NOT exist %PREFIX%/lib/progressbar_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/progressbar
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'C library for displaying text progress bars'
  dev_url: https://github.com/limix/progressbar

extra:
  recipe-maintainers:
    - Horta
