travis:
  secure:
    BINSTAR_TOKEN: ogYegfDE89Pv+ao0iX4IEtuaXbNb2QoM0XGlkhMLd+3RCRdFxV30qkrhgdLNgRZp16RgBQLsmFu31zhZ4dLT7fBvKgiuP/g4yZcFqhFBDsYKK4+PLs/lhVR5EZHgP730Zu6faMLGPE1D9FwB408pWRh4ncm+fdz+1oUj/3tplSTfc0FU+lC9TdaPmhOxQUnWOEJFw/ZnFesc4hEiWFm3/RNJ04LV0V6VLJuws2Xk7JhgGKVI/Hxx1iEkrgrkjVbMZ91Ow0hzgmm188QgYBncOLpRdS8YiumDif5l6+7HqmtcDAOHTq1z59De66iKkvWUtMP2Q3TYOhujFkdt+YGkbZZ/fmWwzbQpJFO0xF5kTrHma9C4l8IJLXC++xIXYFjZ/ElB8bNymMDQflzOanJv6tgMt9p9MZjWOIZIvMSIdJJq5SuE0GAyrdqTvW/oLLvomcJlMNCtxmvcZWUJnt1LZBUp3N4MyYeUtl2X+gyrMomuB7junqbGDvuoIVnqL1Kmp88iEGXOM/YF/DxXgr6XnyPgyF10j+7AyZQzhVEAu0d+VSn5+/YcPWJOin0fF5fbeMnqC9D4O2Q78HPNoXDbj1NB0B9FL8B4SLjDhn9ryzmZOZAlpaGI+GVnfP3WI9WuTlL/8+664Rny3YNdAw23fRdRRkmj1a6xH6NrNNA4TVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
