appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: noGE+o2/u20CB0GXUr6rSM5/eAbmumUbUave7LXkrVopNhG1FvPLHO9vsgulvghKQGqa7klTUamWS3uudB4W/nopyp1TaXTYIEppb46b7u5ejAaGy9tDMvYTMoPgQiJp4I2D8/4ZRUGtKhK7GfQkkqtIALQve28IFOLCRz1d/XtCxSGmz2+hgWYqFHkTsrE+12EhHwSkkDIvZ4H7ZIIw/lEp9a6sRT42F1X6gdpVKU2CbBCGbRDdeVDQJ2Jn5eFD4bewWFSkFukSTlQdF7wSCCO4geesFyQEhGg3ky7cBmPgpsHX/0ImF9mR1XOrMs8luKZOrxpGrfDXZthZ8iEKP7gP6jHPpOviVe9Yvre5umvi4Vij6WyQqU1dzAw8jiOwB/E6Qc37ENeEnyOqZXWxUIPCLUWpKpQPtq2EVebU2AkRQGH99HtXzNRoIIuVVEd6jzDnRTI5kRBI86djJ+L8slJTd+MBQBLV+nfqE1yibkgYioNqMxsQAqGwdTU5qgGebMb+ejAJtQfNTaXwUr5rKK8SavIHj0fa9L9g3M6Ith5GO4ndeqqN42YNWFiKU7gFsHtdW4SpK0HKsHrJAfvUFfn6yF2o+92WfCXuOk57QBcRwBqyPcKm/RHBB1aAqA/l0RIpjz9w9adwDZK045igMGqH3Oo0vuIOVTXJ8rHWDzc=}
conda_forge_output_validation: true
